DROP TABLE IF EXISTS claims;

CREATE TABLE claims (
    months_as_customer          INTEGER,
    age                         INTEGER,
    policy_number               TEXT,
    policy_bind_date            TEXT,
    policy_state                TEXT,
    policy_csl                  TEXT,
    policy_deductable           INTEGER,
    policy_annual_premium       NUMERIC(10, 2),
    umbrella_limit              NUMERIC(15, 2),
    insured_zip                 TEXT,
    insured_sex                 TEXT,
    insured_education_level     TEXT,
    insured_occupation          TEXT,
    insured_hobbies             TEXT,
    insured_relationship        TEXT,
    capital_gains               NUMERIC(15, 2),
    capital_loss                NUMERIC(15, 2),
    incident_date               TEXT,
    incident_type               TEXT,
    collision_type              TEXT,
    incident_severity           TEXT,
    authorities_contacted       TEXT,
    incident_state              TEXT,
    incident_city               TEXT,
    incident_location           TEXT,
    incident_hour_of_day        INTEGER,
    number_of_vehicles_involved INTEGER,
    property_damage             TEXT,
    bodily_injuries             INTEGER,
    witnesses                   INTEGER,
    police_report_available     TEXT,
    total_claim_amount          NUMERIC(15, 2),
    injury_claim                NUMERIC(15, 2),
    property_claim              NUMERIC(15, 2),
    vehicle_claim               NUMERIC(15, 2),
    auto_make                   TEXT,
    auto_model                  TEXT,
    auto_year                   INTEGER,
    fraud_reported              TEXT
);